version: '3.4'

services:
  energypricehelper:
    container_name: api
    restart: always
    image: energypricehelper
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/app

  web:
    restart: always
    container_name: web
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development