import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { url } from "inspector";
import FileUploadSingle from "../components/FileUploadSingle";
import FileDownload from "../components/FileDownload";

const inter = Inter({ subsets: ["latin"] });
const axios = require("axios");

export default function Home() {
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);

  const getData = async() => {
    const res = await (await fetch('http://localhost:5000/api/main')).json()
    setData(res['hello'])
  }

  useEffect(() => {
     getData()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </div>

        <FileUploadSingle />
        <FileDownload />

      </main>
    </>
  );
}
